version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80" # Nginx serves on 80 inside container
    depends_on:
      - mapping-service
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  mapping-service:
    build:
      context: .
      dockerfile: services/mapping-service/Dockerfile
    ports:
      - "8000:8000"
